/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screens;

import Methods.ReadTxtFile;
import p_case.*;
import Methods.TXTReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Simon
 */
public class ListScreen extends javax.swing.JFrame {

    /**
     * Creates new form ListScreen
     */
    public ListScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelU_name = new javax.swing.JLabel();
        jButtonLogout = new javax.swing.JButton();
        jButtonNewListing = new javax.swing.JButton();
        jButtonHelp = new javax.swing.JButton();
        jButtonChange_Delete = new javax.swing.JButton();
        jLabelDomain = new javax.swing.JLabel();
        jLabelPasswort = new javax.swing.JLabel();
        jLabelBenutzername = new javax.swing.JLabel();
        jLabelNummer = new javax.swing.JLabel();
        jButtonTest = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaDomain = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaPasswort = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaBenutzername = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextAreaNummer = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("P_CASE");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(91, 91, 91));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));

        jLabelU_name.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabelU_name.setForeground(new java.awt.Color(0, 0, 0));
        jLabelU_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelU_name.setText("//Username");
        jLabelU_name.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButtonLogout.setBackground(new java.awt.Color(0, 0, 0));
        jButtonLogout.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButtonLogout.setText("Logout");
        jButtonLogout.setToolTipText("Logout");
        jButtonLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLogoutMouseClicked(evt);
            }
        });

        jButtonNewListing.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButtonNewListing.setForeground(new java.awt.Color(0, 0, 0));
        jButtonNewListing.setText("Neuer Eintrag");
        jButtonNewListing.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNewListing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNewListingMouseClicked(evt);
            }
        });

        jButtonHelp.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButtonHelp.setForeground(new java.awt.Color(0, 0, 0));
        jButtonHelp.setText("?");
        jButtonHelp.setToolTipText("Hilfe");
        jButtonHelp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonHelpMouseClicked(evt);
            }
        });

        jButtonChange_Delete.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButtonChange_Delete.setForeground(new java.awt.Color(0, 0, 0));
        jButtonChange_Delete.setText("Bearbeiten / Löschen");
        jButtonChange_Delete.setToolTipText("Bearbeiten / Löschen");
        jButtonChange_Delete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonChange_Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonChange_DeleteMouseClicked(evt);
            }
        });

        jLabelDomain.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabelDomain.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDomain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDomain.setLabelFor(jTextAreaDomain);
        jLabelDomain.setText("Domain");
        jLabelDomain.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelPasswort.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabelPasswort.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPasswort.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPasswort.setLabelFor(jTextAreaPasswort);
        jLabelPasswort.setText("Passwort");
        jLabelPasswort.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelBenutzername.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabelBenutzername.setForeground(new java.awt.Color(0, 0, 0));
        jLabelBenutzername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBenutzername.setLabelFor(jTextAreaBenutzername);
        jLabelBenutzername.setText("Benutzername");
        jLabelBenutzername.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelNummer.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabelNummer.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNummer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNummer.setLabelFor(jTextAreaNummer);
        jLabelNummer.setText("Nummer");
        jLabelNummer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButtonTest.setText("Test");
        jButtonTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonTestMouseClicked(evt);
            }
        });
        jButtonTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTestActionPerformed(evt);
            }
        });

        jTextAreaDomain.setColumns(20);
        jTextAreaDomain.setRows(5);
        jScrollPane5.setViewportView(jTextAreaDomain);

        jTextAreaPasswort.setColumns(20);
        jTextAreaPasswort.setRows(5);
        jScrollPane4.setViewportView(jTextAreaPasswort);

        jTextAreaBenutzername.setColumns(20);
        jTextAreaBenutzername.setRows(5);
        jScrollPane2.setViewportView(jTextAreaBenutzername);

        jTextAreaNummer.setColumns(5);
        jTextAreaNummer.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTextAreaNummer.setForeground(new java.awt.Color(0, 0, 0));
        jTextAreaNummer.setRows(5);
        jScrollPane6.setViewportView(jTextAreaNummer);

        jPanel2.setBackground(new java.awt.Color(6, 200, 248));
        jPanel2.setToolTipText("P_CASE");

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 72)); // NOI18N
        jLabel1.setForeground(java.awt.Color.darkGray);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("P_CASE");
        jLabel1.setToolTipText("P_CASE");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pcaselogo.jpg"))); // NOI18N
        jLabel2.setToolTipText("P_CASE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelU_name)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButtonNewListing, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 44, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNummer, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelBenutzername))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPasswort)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelDomain)
                                    .addComponent(jButtonChange_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)))
                        .addContainerGap(53, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jButtonTest)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonNewListing, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelU_name)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPasswort)
                            .addComponent(jLabelDomain))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelBenutzername)
                            .addComponent(jLabelNummer))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButtonTest))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonChange_Delete)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHelpMouseClicked
        TXTReader reader = new TXTReader();
        JOptionPane.showMessageDialog(null, reader.getFAQs());    }//GEN-LAST:event_jButtonHelpMouseClicked

    private void jButtonChange_DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonChange_DeleteMouseClicked
        
        new Edit().setVisible(true);
        
    }//GEN-LAST:event_jButtonChange_DeleteMouseClicked

    private void jButtonLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogoutMouseClicked
        dispose();
    }//GEN-LAST:event_jButtonLogoutMouseClicked

    private void jButtonNewListingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNewListingMouseClicked
        new NewListing().setVisible(true);
    }//GEN-LAST:event_jButtonNewListingMouseClicked

    private void jButtonTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTestActionPerformed

    private void jButtonTestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTestMouseClicked

        
        ReadTxtFile abc = new ReadTxtFile();
        try {
            abc.FileReaderAdmin(jTextAreaNummer,jTextAreaBenutzername,jTextAreaPasswort);
        } catch (IOException ex) {
            Logger.getLogger(ListScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
      /*  
        ReadTxtFile rtxtf = new ReadTxtFile();
        try {
            rtxtf.FileReaderUser(jTextAreaTabelle);
        } catch (IOException ex) {
            Logger.getLogger(ListScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
               */
    }//GEN-LAST:event_jButtonTestMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
       
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ListScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChange_Delete;
    private javax.swing.JButton jButtonHelp;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonNewListing;
    private javax.swing.JButton jButtonTest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBenutzername;
    private javax.swing.JLabel jLabelDomain;
    private javax.swing.JLabel jLabelNummer;
    private javax.swing.JLabel jLabelPasswort;
    private javax.swing.JLabel jLabelU_name;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextAreaBenutzername;
    private javax.swing.JTextArea jTextAreaDomain;
    private javax.swing.JTextArea jTextAreaNummer;
    private javax.swing.JTextArea jTextAreaPasswort;
    // End of variables declaration//GEN-END:variables
}
